### ISSUE TITLE
UML naming?

### ISSUE THREAD

**Issue by anrl** [citelab/gini5#23]
UML comes from the days GINI was using User Mode Linux as the Virtual machines.
Now, we are using Docker containers. 

Should we rename them to something else? 

Mach_1 or something else?

**The gBuilder code base has UML in 100s of different places. Here, I am just wanting the UML_x that appears on the screen to change to something else like Mach_x.** 

Yes, the side menu also needs to change consistently.

I tried this with the Docker change and it totally messed up my code. I ended up reverting. So, we need to proceed with caution!

**Comment by trungams** [comment]
wow. I can try but this isn't top priority for now

**Comment by anrl** [comment]
It would be good to have the uml changed to Mach or something on the canvas. I would like to create a tutorial. Having uml is kind of weird.

**Comment by trungams** [comment]
Resolved in branch `uml-rename`
