### ISSUE TITLE
The install script needs to check the setuid 

### ISSUE THREAD

**Issue by anrl** [citelab/gini5#3]
It is necessary to set the setuid for the gBuilder install with regard the "ip" and "bridge" tools to work. The setuid bit has to be changed during the install.

**Comment by trungams** [comment]
This is in regards to scons script right?

**Comment by anrl** [comment]
Yes.
We could check and ask the user to change it.
We are not running the scons install as super user.

**Comment by trungams** [comment]
Closing this issue since we have instruction to change setuid bit in README
